project:
  type: website
  output-dir: docs
  
website:
  title: "RH3_uncertainty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: uncertainty_fact.qmd
        text: Fact
      - href: uncertainty_number.qmd
        text: Number


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

