<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ullrika Sahlin and Dawei Tang">

<title>RH3_uncertainty - Tiered approaches to characterise uncertainty in NGRA exemplified with a risk assessment</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">RH3_uncertainty</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./risk example_aug24.html" rel="" target="" aria-current="page">
 <span class="menu-text">Risk</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#uncertainty-characterisation" id="toc-uncertainty-characterisation" class="nav-link" data-scroll-target="#uncertainty-characterisation">Uncertainty characterisation</a></li>
  <li><a href="#a-tiered-approach-to-reduce-uncertainty" id="toc-a-tiered-approach-to-reduce-uncertainty" class="nav-link" data-scroll-target="#a-tiered-approach-to-reduce-uncertainty">A tiered approach to <strong>reduce</strong> uncertainty</a></li>
  <li><a href="#a-tiered-approach-to-refine-uncertainty" id="toc-a-tiered-approach-to-refine-uncertainty" class="nav-link" data-scroll-target="#a-tiered-approach-to-refine-uncertainty">A tiered approach to <strong>refine</strong> uncertainty</a>
  <ul class="collapse">
  <li><a href="#options-to-refine-the-procedure" id="toc-options-to-refine-the-procedure" class="nav-link" data-scroll-target="#options-to-refine-the-procedure">Options to refine the procedure:</a></li>
  <li><a href="#options-to-refine-the-precision" id="toc-options-to-refine-the-precision" class="nav-link" data-scroll-target="#options-to-refine-the-precision">Options to refine the precision:</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#assessment" id="toc-assessment" class="nav-link" data-scroll-target="#assessment">Assessment</a>
  <ul class="collapse">
  <li><a href="#hazard-assessment" id="toc-hazard-assessment" class="nav-link" data-scroll-target="#hazard-assessment">Hazard assessment</a></li>
  <li><a href="#exposure-assessment" id="toc-exposure-assessment" class="nav-link" data-scroll-target="#exposure-assessment">Exposure assessment</a></li>
  <li><a href="#risk-characterisation" id="toc-risk-characterisation" class="nav-link" data-scroll-target="#risk-characterisation">Risk characterisation</a></li>
  <li><a href="#sources-of-uncertainty" id="toc-sources-of-uncertainty" class="nav-link" data-scroll-target="#sources-of-uncertainty">Sources of uncertainty</a></li>
  </ul></li>
  <li><a href="#practical-certainty" id="toc-practical-certainty" class="nav-link" data-scroll-target="#practical-certainty">Practical certainty</a></li>
  <li><a href="#a-tiered-approach-to-evaluate-the-combined-impact-of-sources-of-uncertainty-on-the-conclusion" id="toc-a-tiered-approach-to-evaluate-the-combined-impact-of-sources-of-uncertainty-on-the-conclusion" class="nav-link" data-scroll-target="#a-tiered-approach-to-evaluate-the-combined-impact-of-sources-of-uncertainty-on-the-conclusion">A tiered approach to evaluate the combined impact of sources of uncertainty on the conclusion</a></li>
  <li><a href="#tier-1.-basic-option" id="toc-tier-1.-basic-option" class="nav-link" data-scroll-target="#tier-1.-basic-option">Tier 1. Basic option</a></li>
  <li><a href="#tier-2.-refined-option-with-probability-bounds" id="toc-tier-2.-refined-option-with-probability-bounds" class="nav-link" data-scroll-target="#tier-2.-refined-option-with-probability-bounds">Tier 2. Refined option with probability bounds</a>
  <ul class="collapse">
  <li><a href="#probabilities-first" id="toc-probabilities-first" class="nav-link" data-scroll-target="#probabilities-first">Probabilities first</a></li>
  <li><a href="#numbers-first" id="toc-numbers-first" class="nav-link" data-scroll-target="#numbers-first">Numbers first</a></li>
  </ul></li>
  <li><a href="#tier-3.-refined-option-with-probability-distributions" id="toc-tier-3.-refined-option-with-probability-distributions" class="nav-link" data-scroll-target="#tier-3.-refined-option-with-probability-distributions">Tier 3. Refined option with probability distributions</a>
  <ul class="collapse">
  <li><a href="#point-of-departure" id="toc-point-of-departure" class="nav-link" data-scroll-target="#point-of-departure">Point of Departure</a></li>
  <li><a href="#high-exposure" id="toc-high-exposure" class="nav-link" data-scroll-target="#high-exposure">High Exposure</a></li>
  <li><a href="#calculated-risk-ratio" id="toc-calculated-risk-ratio" class="nav-link" data-scroll-target="#calculated-risk-ratio">Calculated risk ratio</a></li>
  <li><a href="#consider-additional-sources-of-uncertainty" id="toc-consider-additional-sources-of-uncertainty" class="nav-link" data-scroll-target="#consider-additional-sources-of-uncertainty">Consider additional sources of uncertainty</a></li>
  </ul></li>
  <li><a href="#comments-on-the-uncertainty-framework" id="toc-comments-on-the-uncertainty-framework" class="nav-link" data-scroll-target="#comments-on-the-uncertainty-framework">Comments on the uncertainty framework</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tiered approaches to characterise uncertainty in NGRA exemplified with a risk assessment</h1>
<p class="subtitle lead">RiskHunt3R meeting Aug 2024</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ullrika Sahlin and Dawei Tang </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level1">
<h1>Introduction</h1>
<section id="uncertainty-characterisation" class="level2">
<h2 class="anchored" data-anchor-id="uncertainty-characterisation">Uncertainty characterisation</h2>
<p>Uncertainty in an assessment is characterised by</p>
<ol type="1">
<li><p>identifying sources of uncertainty and</p></li>
<li><p>evaluating their combined impact on the conclusion</p></li>
</ol>
</section>
<section id="a-tiered-approach-to-reduce-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="a-tiered-approach-to-reduce-uncertainty">A tiered approach to <strong>reduce</strong> uncertainty</h2>
<ul>
<li>If practical certainty is not obtained, collect more data</li>
</ul>
</section>
<section id="a-tiered-approach-to-refine-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="a-tiered-approach-to-refine-uncertainty">A tiered approach to <strong>refine</strong> uncertainty</h2>
<ul>
<li><p>If practical certainty is not obtained, and it is not justified to collect more data, refine the characterisation of uncertainty</p></li>
<li><p>Follow options for increased refinement until practical certainty is obtained or stop with an inconclusive assessment</p></li>
</ul>
<section id="options-to-refine-the-procedure" class="level3">
<h3 class="anchored" data-anchor-id="options-to-refine-the-procedure">Options to refine the procedure:</h3>
<ul>
<li><p>Use worst case assumptions and characterise uncertainty in conclusion directly by expert judgement</p></li>
<li><p>Break down the assessment into parts, characterise uncertainty in each part, combine by calculations, and make expert judgement considering additional sources of uncertainty</p></li>
</ul>
</section>
<section id="options-to-refine-the-precision" class="level3">
<h3 class="anchored" data-anchor-id="options-to-refine-the-precision">Options to refine the precision:</h3>
<ul>
<li><p>Start with probability bounds (Numbers) and combine by Probability Bounds Analysis</p></li>
<li><p>If applicable, proceed with reducing bounds on probabilities</p></li>
<li><p>Otherwise, proceed with specifying full probability distributions and combine by probability calculations or Monte Carlo simulation.</p></li>
</ul>
</section>
</section>
</section>
<section id="assessment" class="level1">
<h1>Assessment</h1>
<p>Consider a human health risk assessment of chemical <span class="math inline">\(X\)</span>.</p>
<section id="hazard-assessment" class="level2">
<h2 class="anchored" data-anchor-id="hazard-assessment">Hazard assessment</h2>
<p>The quantity of interest for the hazard assessment is the Point of Departure, <strong>PoD</strong>.</p>
<p>As an example, a PoD of 0.07 μg <span class="math inline">\(X\)</span>/kg bw per day was identified by the experts as the BMDL from a model average of BMD modelling for a relevant human effect.</p>
<p>Model Averaged BMD model</p>
<table class="table">
<thead>
<tr class="header">
<th>BMDL</th>
<th>BMD</th>
<th>BMDU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.07</td>
<td>1.06</td>
<td>1.3</td>
</tr>
</tbody>
</table>
</section>
<section id="exposure-assessment" class="level2">
<h2 class="anchored" data-anchor-id="exposure-assessment">Exposure assessment</h2>
<p>The quantity of interest for the exposure assessment is a High Exposure in the target population, <strong>HE</strong>.</p>
<p>Estimate of high exposure μg/kg bw per day for compound <span class="math inline">\(X\)</span> is</p>
<table class="table">
<thead>
<tr class="header">
<th>HEL</th>
<th>HE</th>
<th>HE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.1</td>
<td>0.36</td>
<td>1.34</td>
</tr>
</tbody>
</table>
<p>for the given exposure scenario.</p>
</section>
<section id="risk-characterisation" class="level2">
<h2 class="anchored" data-anchor-id="risk-characterisation">Risk characterisation</h2>
<p>The question for the risk assessment is if the High Exposure is below the Point of Departure, i.e.</p>
<p><span class="math display">\[HE &lt; PoD\]</span></p>
<p>The answer to the assessment question is <strong>NO HEALTH CONCERN</strong> if the ratio <span class="math inline">\(\frac{\hat{HE}}{\hat{PoD}} &lt; 1\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When the PoD is derived from BMD modelling, a ratio greater than 1 implies that the exposure can be associated with a 5% increase relative to the background incidence for the effect. Note that the value 5% comes from the BMD modelling.</p>
</div>
</div>
</section>
<section id="sources-of-uncertainty" class="level2">
<h2 class="anchored" data-anchor-id="sources-of-uncertainty">Sources of uncertainty</h2>
<p>The first step in an uncertainty analysis is to identify sources of uncertainty related to inputs and methods.</p>
<p>Sources of uncertainty can be summarised as tables with explanations and indications on their influence on the overall uncertainty (qualitative expressions).</p>
</section>
</section>
<section id="practical-certainty" class="level1">
<h1>Practical certainty</h1>
<p>The practical certainty is by risk managers set to be 80% probability to conclude that compound <span class="math inline">\(X\)</span> is a health concern and 90% probability to conclude that compound <span class="math inline">\(X\)</span> is not a health concern. The assessment is <em>inconclusive</em> for any (un)certainty in between the limits.</p>
<p>It can be sufficient to conclude if uncertainty the conclusion is in the range of practical certainty.</p>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 45%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>No health concern</th>
<th>Inconclusive</th>
<th>Yes health concern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt;10%</td>
<td>10 - 80</td>
<td>&gt;80%</td>
</tr>
</tbody>
</table>
<p>or</p>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 45%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Health concern</th>
<th>Inconclusive</th>
<th>No health concern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt;20%</td>
<td>20 - 90</td>
<td>&gt;90%</td>
</tr>
</tbody>
</table>
<p>If not, the assessment should be reported as <strong>inconclusive</strong>. The risk managers can then decide to support generation of new studies to <strong>reduce</strong> uncertainty by collecting more data or perform a re-evaluation of the risk assessment with a more <strong>refined</strong> characterisation of uncertainty.</p>
</section>
<section id="a-tiered-approach-to-evaluate-the-combined-impact-of-sources-of-uncertainty-on-the-conclusion" class="level1">
<h1>A tiered approach to evaluate the combined impact of sources of uncertainty on the conclusion</h1>
<p>There are several options to evaluate the combined impact of all these sources of uncertainty on the conclusion whether the risk ratio is greater than 1.</p>
<p>A tiered uncertainty analysis can be done in the following steps</p>
<ol type="1">
<li><p>Basic option</p></li>
<li><p>Refined option with uncertainty expressed by probability bounds</p></li>
<li><p>Refined options with uncertainty expressed by probability distributions</p></li>
</ol>
<p>In each step, summarise uncertainty in the conclusion as % probability for the more probable outcome.</p>
<p>Check if the % probability for the more probable outcome is in the region of practical certainty.</p>
</section>
<section id="tier-1.-basic-option" class="level1">
<h1>Tier 1. Basic option</h1>
<p>The basic option is to assess the combined impact in a single step using expert judgement. This is done by asking the experts to agree how certain they are as a group that <span class="math inline">\(\frac{HE}{PoD} &lt; 1\)</span>, considering all evidence and all identified (non-standard or standard) sources of uncertainty.</p>
<p>This can be done by reaching a consensus judgement, following procedures for expert knowledge elicitation (using behavioural aggregation to allow for discussions). This judgement requires expertise on both toxicity and exposure assessment.</p>
<p>This judgement is more easy when the conservative estimate for the Highest Exposure is far below (a conservative value for) the Point of Departure. Here</p>
<p><span class="math inline">\(\frac{HE}{PoD} = \frac{1.34}{0.07} = 19.1\)</span> which is above the threshold.</p>
<p>Conservative values can be obtained by uncertainty factors. It is preferable to have well-calibrated uncertainty factors as they will result in estimates with known level of conservatism. If not, it is difficult for the experts to judge their uncertainty in the conclusion.</p>
<p>In our example, the expert agree that their (un)certainty lies in the inconclusive range. Some of them say that they can not make this judgement, which would also leed to an inconclusive assessment.</p>
<p>Is practical certainty obtained? No.</p>
<p>We proceed by <strong>refining</strong> uncertainty</p>
</section>
<section id="tier-2.-refined-option-with-probability-bounds" class="level1">
<h1>Tier 2. Refined option with probability bounds</h1>
<p>A refined approach is useful when there is a small difference between the Point of Departure and the Highest Exposure, when the experts cannot conclude and collecting more data is not possible within the limits of the assessment.</p>
<p>A refined option is to assess uncertainties separately for the <strong>PoD</strong> and <strong>HE</strong>, combine them by calculations into a risk ratio and assess uncertainty in the conclusion.</p>
<p>We explore how to do this with <strong>probability bound analysis</strong> where we offer two approaches:</p>
<ul>
<li><p>probabilities first: to elicit quantiles for given probabilities, where the probabilities are chosen to obtain practical certainty</p></li>
<li><p>numbers first: to elicit probabilities given numerical values, where the numerical values are chosen so the risk ratio is 1.</p></li>
</ul>
<!-- Also know as the *glorious formulas* -->
<section id="probabilities-first" class="level2">
<h2 class="anchored" data-anchor-id="probabilities-first">Probabilities first</h2>
<p>The refined option with probability bounds can be modified to consider practical certainty in the following way. In this example, the risk managers and the experts have agreed that experts must be at least 90% certain that a High Exposure <strong>HE</strong> is below the <strong>PoD</strong> in order for risk managers to make a decision.</p>
<p>This means that the assessment is conclusive when the experts are at least 90% certain that the risk ratio is less than one (<em>no health concern</em>).</p>
<p>Subtract the probability threshold for practical certainty from 100% to set an upper bound for the the sum of the lost probabilities.</p>
<p><span class="math display">\[100\% - 90\% = 10\%\]</span></p>
<p>Divide the resulting probability into two parts, one for the hazard, here <span class="math inline">\(5\%\)</span>, and one for the exposure, what remains <span class="math inline">\(100-90 - 5 = 5\%\)</span>.</p>
<p>Elicit the conservative estimate of the Point of Departure from the toxicology experts (asking them to consider the identified sources of uncertainty for the hazard assessment). Define the conservative estimate as the quantile <span class="math inline">\(y\)</span></p>
<p><span class="math display">\[P(PoD &lt; y) = 5\%\]</span></p>
<p>Here the expert set <span class="math inline">\(y = 0.07\)</span>, which is the BMDL. Experts can adjust this downward or upward considering additional sources of uncertainty.</p>
<p>Elicit a conservative estimate of a High Exposure from the exposure experts (asking them to consider the identified sources of uncertainty for the exposure assessment, alternatively any additional sources of uncertainty not accounted for in a model based conservative estimate). Define the conservative estimate as the quantile <span class="math inline">\(x\)</span></p>
<p><span class="math display">\[P(HE &gt; x) = 5\%\]</span></p>
<p>In this example, the expert elicit the value <span class="math inline">\(x = 1.32\)</span>.</p>
<p>Divide the conservative estimate for the exposure with the conservative estimate for the hazard <span class="math inline">\(\frac{x}{y}\)</span>.</p>
<p>Practical certainty is obtained if <span class="math inline">\(\frac{x}{y} &lt; 1\)</span>.</p>
<p>In this example, this ratio is <span class="math inline">\(\frac{1.32}{0.07} = 18.9\)</span></p>
<p>Practical certainty is not reached with the probability bounds analysis using probabilities first, proceed with a refined approach.</p>
<!-- Hence, practical certainty is reached. Proceed to the decision. -->
</section>
<section id="numbers-first" class="level2">
<h2 class="anchored" data-anchor-id="numbers-first">Numbers first</h2>
<p>Use a conservative estimate for PoD as starting point and use experts judgement on their uncertainty for that to guide what value to consider for the exposure part.</p>
<p>Ask experts to judge their probability expressing their uncertainty about a conservative estimate of hazard, e.g.&nbsp;the BMDL,</p>
<p>The experts judge that they are 5% certain that the Point of Departure is below 0.07 μg <span class="math inline">\(X\)</span>/kg bw per day.</p>
<p><span class="math display">\[P(PoD &lt; y) = 5\%\]</span> That implies that the conservative estimate for the hazard is <span class="math inline">\(y = 0.07\)</span>, which is the BMDL. Experts can adjust this downward or upward considering additional sources of uncertainty.</p>
<table class="table">
<thead>
<tr class="header">
<th>P below</th>
<th>value</th>
<th>P above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>5%</td>
<td>y</td>
<td>95%</td>
</tr>
</tbody>
</table>
<!-- In some situations, the PoD is the BMDL and then it is difficult to talk about uncertainty about the PoD. If so, one can introduce an uncertainty factor (UF) that considers uncertainty associated with the hazard assessment. The focus is then on PoD/UF instead of PoD. -->
<p>Derive the value on the High Exposure where the risk ratio is at the critical threshold</p>
<p><span class="math display">\[\frac{x}{y} = 1\]</span></p>
<p>This value is <span class="math inline">\(x = 1 \cdot y = 0.07\)</span></p>
<p>Ask the experts to judge their probability that a High Exposure is above 0.07 μg <span class="math inline">\(X\)</span>/kg bw per day. The experts’ elicited probability is 98.1%.</p>
<p><span class="math display">\[P( HE &gt; x) = 98.1\%\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th>P below</th>
<th>value</th>
<th>P above</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.9%</td>
<td>x</td>
<td>98.1%</td>
</tr>
</tbody>
</table>
<p>Practical certainty is obtained if <span class="math display">\[100 - P(HE &gt; x) - P(PoD &lt; y) \geq 90\]</span> In this example, the left hand side is <span class="math inline">\(100-[98.1+5]=100-98.1 - 5= -3.1\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that probabilities cannot be negative. Here, the negative value is a result from using a simplified probabilistic where probabilities are added up.</p>
</div>
</div>
<p>Hence, practical certainty is not reached with the probability bounds analysis using numbers first.</p>
<p>If it is not possible to conclude with high enough certainty, we move on to a refined option for uncertainty analysis with probability distributions or consider reducing uncertainty by collecting more data.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The numbers and probabilities are chosen for demonstration. There might be inconsistencies in the judgements between the “probability-first” and “numbers-first” approaches in this example. In reality, only one of the options are chosen.</p>
</div>
</div>
</section>
</section>
<section id="tier-3.-refined-option-with-probability-distributions" class="level1">
<h1>Tier 3. Refined option with probability distributions</h1>
<p>A refined option can alternatively be done with probability distributions which are combined by calculations or Monte Carlo simulation.</p>
<p>This is an option, when the outcome of a probability bound analysis was inconclusive.</p>
<p>It can also be an option when the assessors prefers to choose to justify probability distributions for uncertainty from available information, combine uncertainties by performing the probability calculations, and then ask the experts to consider additional sources of uncertainty (not yet accounted for) by making a judgement on the outcome of interest directly.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that an explicit elicitation of the outcome of interest following a Monte Carlo simulation is a condition for this approach to result in a characterisation of the experts uncertainty considering the combined impact of <strong>all</strong> sources of uncertainty in the assessment.</p>
</div>
</div>
<section id="point-of-departure" class="level3">
<h3 class="anchored" data-anchor-id="point-of-departure">Point of Departure</h3>
<p>A probability distribution representing uncertainty in the <strong>Point of Departure</strong> can be taken from the BMD uncertainty distribution generated by bootstrapping or Bayesian modelling. There are plenty of BMD software available to do this.</p>
<p>We (the assessors) let the BMDL, the BMD, and the BMDU define a lower percentile (0.05), the median (0.5), and a higher percentile (0.95) of the probability distribution for uncertainty in the <strong>PoD</strong>.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>BMDL</th>
<th>BMD</th>
<th>BMDU</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P</td>
<td>5</td>
<td>50</td>
<td>95</td>
</tr>
<tr class="even">
<td>Value</td>
<td>0.07</td>
<td>1.06</td>
<td>1.3</td>
</tr>
</tbody>
</table>
<p>The lower bound is zero. The distribution for a BMD is usually skewed to the right, and therefore the experts set an upper plausible bound. Here we fit a distribution to these quantiles using a quantile matching method and draw samples from this distribution.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<!-- ::: callout-tip -->
<!-- An alternative is to go to the online elicitation app for one distribution [link to SHELF app](https://jeremy-oakley.shinyapps.io/SHELF-single/) and find a probability distribution that matches these quantiles. Note that you have to specify the lower and upper bound of the plausible range. You can get them from studying the sample from BMD modelling. You can find the R-code to generate random numbers from the selected probability distribution in the report that is possible to download from SHELF -->
<!-- ::: -->
<!-- We sample from the fitted distribution using this R-code -->
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>This approach ignores additional sources of uncertainty than those considered in the model, hence we need to draft how to consider those as well. e.g.&nbsp;by adjusting the specification of the quantiles.</p>
</div>
</div>
</section>
<section id="high-exposure" class="level3">
<h3 class="anchored" data-anchor-id="high-exposure">High Exposure</h3>
<p>A probability distribution representing uncertainty in the estimates of High Exposure is informed by a Monte Carlo simulation sample of the 95th percentile of the Cmax in the target population. Here we have at the quartiles from such a sample. Since we have a sample, we can have more quantiles.</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>min HE</th>
<th>median HE</th>
<th>max HE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P</td>
<td>5</td>
<td>50</td>
<td>95</td>
</tr>
<tr class="even">
<td>value</td>
<td>0.1</td>
<td>0.36</td>
<td>1.34</td>
</tr>
<tr class="odd">
<td>log value</td>
<td>-2.3025851</td>
<td>-1.0216512</td>
<td>0.2926696</td>
</tr>
</tbody>
</table>
<p>One choice could be to use a lognormal distribution to represent uncertainty in a High Exposure. A lognormal distribution has two parameters, the mean (<span class="math inline">\(\mu\)</span>) and the standard deviation (<span class="math inline">\(\sigma\)</span>) on the log scale. Note that quantiles are preserved across monotonic transformations.</p>
<p><span class="math display">\[logHE \sim N(\mu,\sigma)\]</span></p>
<p>Here is a simple way to do it. One can also fit a distribution by quantile matching. The standard deviation is specified by considering the formula for a 90% quantile in the normal distributions as a function of the parameters:</p>
<p><span class="math display">\[ P95 = \mu + 1.64\cdot \sigma\]</span></p>
<p>and rearranging it to be a function of <span class="math inline">\(\sigma\)</span></p>
<p><span class="math display">\[ \sigma = \frac{P95 - \mu}{1.64} =  \frac{0.29--1.02}{1.64}=0.8\]</span></p>
<p>Specification of the parameters and draw of random numbers from the normal distribution.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="calculated-risk-ratio" class="level3">
<h3 class="anchored" data-anchor-id="calculated-risk-ratio">Calculated risk ratio</h3>
<section id="combine-sources-of-uncertainty-by-calculations" class="level4">
<h4 class="anchored" data-anchor-id="combine-sources-of-uncertainty-by-calculations">Combine sources of uncertainty by calculations</h4>
<p>Evaluate the combined impact of the characterised uncertainty in PoD and HE on the risk ratio by Monte Carlo simulation.</p>
<p>The distributions for High Exposure and the Point of Departure overlap.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The calculated probability that the risk ratio is below 1 is <span class="math display">\[P(HE&lt;PoD)=P(\frac{HE}{PoD}&lt;1) = 90 \%\]</span></p>
<p>This value was derived by calculating the proportion of random samples in your Monte Carlo simulation that corresponds to a ratio &lt; 1.</p>
</section>
<section id="visualisation" class="level4">
<h4 class="anchored" data-anchor-id="visualisation">Visualisation</h4>
<p>Depending on what is the more probable outcome, there are alternatives to visualise uncertainty in the risk ratio: Framing as no health concern and Framing as a health concern. We recommend to choose the framing that corresponds to the more probable outcome.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this visualisation, the red area corresponds to a High Exposure less than the Point of Departure.</p>
<p>Another way is to visualise the resulting distribution for uncertainty in the risk ratio by outcome that there is a health concern.</p>
<p>The calculated probability that the risk ratio is above 1 is <span class="math display">\[P(HE&gt;PoD)=P(\frac{HE}{PoD}&gt;1) = 10 \%\]</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>In this visualisation, the red area corresponds to a High Exposure greater than the Point of Departure.</p>
</section>
</section>
<section id="consider-additional-sources-of-uncertainty" class="level3">
<h3 class="anchored" data-anchor-id="consider-additional-sources-of-uncertainty">Consider additional sources of uncertainty</h3>
<p>As a final step, the experts are invited to adjust this probability upwards or downwards considering <strong>additional sources of uncertainty</strong>, not previously taken into account in the analysis.</p>
<p>An additional sources of uncertainty could e.g.&nbsp;be the choice of distributions used in the Monte Carlo simulation and any limitations in the quality of the exposure and toxicity data that are not taken into account in those distributions.</p>
<p>Experts might judge that any additional sources of uncertainty will have little influence and that there is no need to adjust the calculated % probability that the risk ratio is less (or greater) than 1.</p>
<p>If not, experts can choose to consider any additional uncertainties by adjusting the PoD or HE by an uncertainty factor. This factor can be described as a probability distribution or have a single number. It could be factor for exposure and a factor for hazard.</p>
<p><span class="math display">\[P(HE\cdot f_{HE} &lt; PoD \cdot f_{PoD})\]</span></p>
<p>Here the experts argue that the exposure is overly conservative, and can be adjusted down by a factor, i.e.&nbsp;<span class="math inline">\(f_{HE} = 0.5\)</span>. They also reason that there is no impact from additional sources of uncertainty on the Point of Departure <span class="math inline">\(f_{PoD} = 1\)</span></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Here the expert judge that their % certainty for no health concern is 98%.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="risk-example_aug24_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>This value is in the region of practical certainty (i.e.&nbsp;&gt;90%) and therefore the uncertainty characterisation is completed and one can proceed with decision making.</p>
</section>
</section>
<section id="comments-on-the-uncertainty-framework" class="level1">
<h1>Comments on the uncertainty framework</h1>
<p>Bayesian reasoning combined with Probability bounds analysis can be used for categorical as well as continuous quantities.</p>
<p>Probability bounds can be specified by bounded probability, e.g.&nbsp;<span class="math inline">\(P(PoD &gt; y) &lt; 90\%\)</span> instead of <span class="math inline">\(P(PoD &gt; y) = 90\%\)</span>.</p>
<p>The basic option requires one expert judgement.</p>
<p>The probability bound analysis option requires two expert judgements.</p>
<p>The precise probabilistic option can use information from the probability bound analysis and complement it with at least two more expert judgements. Usually more quantiles are provided from modelling, which in turn is based in multiple expert judgements (for the parameter uncertainty). The probability distributions representing uncertainty in PoD and a High Exposure can be more or less derived from quantitative modelling in which uncertainty within the model is characterised, but consideration of additional sources of uncertainty e.g.&nbsp;as factors are always needed.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>